---
- name: install flatpak package
  zypper: name=flatpak state=present

- name: add 'flathub' remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: refresh metadata from flatpak remotes
  command: flatpak update --appstream
