---
- name: install sudo
  package: name=sudo state=present

- name: install wheel group provider
  package: name=system-group-wheel state=present

- name: copy sudoers config
  copy:
    src: files/sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    validate: 'visudo -c -f %s'
    mode: 0440

- name: lock root user account
  command: passwd -l root
