---
- name: copy first snapshot metadata
  copy:
    src: files/info.xml
    dest: /.snapshots/1/info.xml

- name: init snapper config
  copy:
    src: /usr/share/snapper/config-templates/default
    dest: /etc/snapper/configs/root
  when: is_version_gte_154 == true

# Legacy file location (snapper <= 0.8)
- name: init snapper config (legacy)
  copy:
    src: /etc/snapper/config-templates/default
    dest: /etc/snapper/configs/root
  when: is_version_gte_154 == false

- name: disable copy on write on /var
  file:
    path: /var
    attributes: +C

- name: enable booting from snapshots
  lineinfile:
    path: /etc/default/grub
    regexp: '^SUSE_BTRFS_SNAPSHOT_BOOTING'
    line: 'SUSE_BTRFS_SNAPSHOT_BOOTING=true'
