---
- name: copy first snapshot metadata
  template:
    src: files/info.xml.j2
    dest: /.snapshots/1/info.xml
    mode: '0600'
  vars:
    date_utc: "{{ now(utc=True, fmt='%Y-%m-%d %H:%M:%S') }}"

- name: disable copy on write on /var
  file:
    path: /var
    attributes: +C
  register: chattr_cow
  failed_when: "chattr_cow.failed and 'not supported' not in chattr_cow.details"

- name: ensure correct permissions on /.snapshots
  file:
    path: /.snapshots
    owner: root
    group: root
    mode: '0750'

- name: remove hardcoded root subvolume
  replace:
    regexp: 'subvol=/@/.snapshots/1/snapshot'
    path: /etc/fstab

- name: enable btrfs quota support
  command: btrfs quota enable /

- name: create qgroup for cleanup algorithms
  command: btrfs qgroup create 1/0 /
