---
- name: install microsoft fonts
  package: name=fetchmsttfonts state=present
  when: install_fetchmsttfonts == true

- name: set default tty console font
  lineinfile:
    path: /etc/vconsole.conf
    regexp: '^FONT='
    line: 'FONT=eurlatgr.psfu'

- name: copy font config
  template: src=fonts-config.j2 dest=/etc/sysconfig/fonts-config
  notify:
    - apply fonts-config
