---
- name: add 'flathub' remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: refresh metadata from flatpak remotes
  command: flatpak update --appstream

- name: install breeze gtk for flatpak
  flatpak: name=org.gtk.Gtk3theme.Breeze state=present
