---
- name: sets graphical target
  command: systemctl set-default graphical.target

- import_tasks: flatpak.yml

- name: enable laptop services
  systemd: name={{item}} enabled=yes
  with_items:
    - thermald
    - tlp

- name: workaround - enable wireplumber for all users
  systemd:
    name: wireplumber
    scope: global
    enabled: yes
