---
- name: setup network
  block:
    - import_tasks: networkmanager.yml
    - import_tasks: dns.yml
  when: conf_stage == 'image_setup'

- import_tasks: dns_symlink.yml
  when: conf_stage in ('image_boot', 'system_install')
