---
- name: install desktop apps
  zypper:
    name:
      - chromium
      - dolphin
      - konsole
      - kwrite
      - kcalc
      - partitionmanager
      - kolourpaint
      - kcolorchooser
      - okular
      - ark
      - gwenview
      - transmission-qt
      - ksysguard5
      - discover
      - discover-backend-packagekit
      - discover-backend-flatpak
      - kwalletmanager5
      - spectacle
      - filelight
      - keepassxc
      - vlc-qt
      - youtube-dl
    state: present

- name: install fwupd backend for Discover
  zypper: name=discover-backend-fwupd state=present
  when: is_version_gte_152 == true
