---
- name: install desktop apps
  zypper:
    name:
      - dolphin
      - konsole
      - kwrite
      - kcalc
      - partitionmanager
      - kcolorchooser
      - ark
      - ksysguard5
      - discover
      - discover-notifier
      - discover-backend-flatpak
      - discover-backend-fwupd
      - kwalletmanager5
      - spectacle
    state: present
