---
- name: install desktop apps
  zypper:
    name:
      - chromium
      - dolphin
      - konsole
      - kwrite
      - kcalc
      - partitionmanager
      - kolourpaint
      - kcolorchooser
      - okular
      - ark
      - gwenview
      - transmission-qt
      - ksysguard5
      - discover
      - discover-backend-packagekit
      - discover-backend-flatpak
      - discover-backend-fwupd
      - kwalletmanager5
      - spectacle
      - filelight
      - keepassxc
      - vlc-qt
      - youtube-dl
    state: present
