---
- name: install general desktop base
  zypper:
    name:
      - zigzag-wallpapers
      - xdg-user-dirs
      - xdg-utils
      - gsettings-backend-dconf
      - alsa-firmware
      - alsa-utils
      - bluez-firmware
      - PackageKit-backend-zypp
      - PackageKit-gstreamer-plugin
      - udisks2
    state: present

- name: install pulseaudio
  zypper:
    name:
      - pulseaudio
      - pulseaudio-module-bluetooth
      - pulseaudio-module-zeroconf
      - pulseaudio-module-x11
      - alsa-plugins-pulse
    state: present
  when: is_version_gte_153 == false

- name: install pipewire
  zypper:
    name:
    - pipewire
    - pipewire-modules
    - pipewire-alsa
    - pipewire-pulseaudio
    - gstreamer-plugin-pipewire
    state: present
  when: is_version_gte_153 == true
