---
- name: install graphics stack and drivers
  zypper:
    name:
      - patterns-zigzag-xfirmware-intel
      - patterns-zigzag-xfirmware-radeon
      - patterns-zigzag-xfirmware-nouveau
      - Mesa-demo-x
      - vulkan-tools
      - xf86-input-libinput
      - libva-utils
      - libva-glx2
    state: present

- name: install x.org
  zypper:
    name:
      - xorg-x11-essentials
      - xorg-x11-server
      - xorg-x11-fonts
      - xorg-x11-driver-video
      - xrandr
      - xclip
      - plasma5-session
    state: present
  when: is_leap == true

- name: install wayland
  zypper:
    name:
      - plasma5-session-wayland
      - wl-clipboard
    state: present
  when: is_tumbleweed == true
