---
# Include non-free packages
non_free: "{{ not lookup('env', 'ZIGZAG_OSS_ONLY') }}"

# Enable development repository
devel_repo: "{{ lookup('env', 'ZIGZAG_DEVEL') | bool }}"

# Check if we're running within kiwi environment
is_kiwi: "{{ lookup('env', 'ZIGZAG_KIWI') | bool }}"

# Distribution checks
is_tumbleweed: "{{ ansible_distribution == 'openSUSE Tumbleweed' }}"
is_leap: "{{ ansible_distribution == 'openSUSE Leap' }}"

# Version checks
is_version_gte_154: "{{ (is_leap and ansible_distribution_version | float >= 15.4) or is_tumbleweed }}"
