---
- hosts: all
  vars:
    conf_stage: image_setup
  pre_tasks:
    # ensure that the rpm database type is not influenced by kiwi host
    # system, resolves the following warning:
    # > Found NDB Packages.db database while attempting bdb backend:
    # > using ndb backend
    - name: rebuild rpm package database
      command: rpm --rebuilddb
  post_tasks:
    - name: install translation packages
      command: zigzag-languages
  roles:
    - zypper
    - base
    - sudo
    - apparmor
    - memory
    - network
    - snapper
    - immutable
    - samba
    - desktop
    - polkit
    - fonts
    - live
