---
- hosts: all
  vars:
    conf_stage: image_setup
  pre_tasks:
    # ensure that the rpm database type is not influenced by kiwi host
    # system, resolves the following warning:
    # > Found NDB Packages.db database while attempting bdb backend:
    # > using ndb backend
    - name: rebuild rpm package database
      command: rpm --rebuilddb

    # this package will be re-added at the later stage, it needs to be
    # removed at the beginning so that it's dependencies are marked as
    # manually installed when we list them in the playbook
    - name: remove dracut-kiwi-live package
      package: name=dracut-kiwi-live state=absent
  post_tasks:
    - name: install translation packages
      command: zigzag-languages
  roles:
    - zypper
    - base
    - sudo
    - apparmor
    - memory
    - network
    - snapper
    - immutable
    - samba
    - desktop
    - polkit
    - fonts
    - live
