# This playbook is executed in the installation process
# after system is copied but before initrd and grub configuration
---
- hosts: all
  vars:
    conf_stage: system_install
  pre_tasks:
    # fix locale settings after installation (opensuse quirk)
    # copy language from /etc/locale.conf to /etc/sysconfig/language
    - name: set the language in /etc/sysconfig/language
      lineinfile:
        path: /etc/sysconfig/language
        regexp: '^RC_LANG'
        line: 'RC_LANG="{{ item }}"'
      with_items: "{{ lookup('ini', 'LANG type=properties file=/etc/locale.conf') }}"
    # calamares only creates the fstab entry if root device is an ssd
    - name: ensure /tmp mountpoint is present in /etc/fstab
      mount:
        path: /tmp
        src: tmpfs
        fstype: tmpfs
        opts: defaults,noatime,mode=1777
        state: present
  roles:
    - live
    - network
    - snapper
    - immutable
