# This playbook is executed in the installation process
# after system is copied but before initrd and grub configuration
---
- hosts: all
  vars:
    conf_stage: system_install
  pre_tasks:
    # fix locale settings after installation (opensuse quirk)
    # copy language from /etc/locale.conf to /etc/sysconfig/language
    - name: set the language in /etc/sysconfig/language
      lineinfile:
        path: /etc/sysconfig/language
        regexp: '^RC_LANG'
        line: 'RC_LANG="{{ item }}"'
      with_items: "{{ lookup('ini', 'LANG type=properties file=/etc/locale.conf') }}"
  # post_tasks:
  #   - name: remove configuration playbooks
  #     file:
  #       path: "{{ playbook_dir }}"
  #       state: absent
  roles:
    - live
    - network
    - snapper
    - immutable
