---
- name: install audio stack
  zypper:
    name:
      - alsa-firmware
      - alsa-utils
      - pipewire
      - pipewire-modules
      - pipewire-alsa
      - pipewire-pulseaudio
      - gstreamer-plugin-pipewire
    state: present
