---
- name: sets graphical target
  command: systemctl set-default graphical.target

- name: enable laptop services
  systemd: name={{item}} enabled=yes
  with_items:
    - thermald
    - tlp

- name: enable tlp-sleep if service exists
  systemd: name=tlp-sleep enabled=yes
  ignore_errors: yes # for tlp 1.3+ service no longer exists
