---
- name: sets graphical target
  command: systemctl set-default graphical.target

- name: enable laptop services
  systemd: name={{item}} enabled=yes
  with_items:
    - thermald
    - tlp

- name: enable tlp-sleep
  systemd: name=tlp-sleep enabled=yes
  when: is_version_gte_153 == false
