---
- name: install x.org
  zypper:
    name:
      - xorg-x11-essentials
      - xorg-x11-server
      - xorg-x11-fonts
      - xorg-x11-driver-video
      - xrandr
      - xclip
      - plasma5-session
    state: present
