---
- name: install translation packages
  command: zigzag-languages

- name: install live medium tools
  zypper:
    name:
      - calamares-branding-zigzag
      - zigzag-live-service
      - dracut-kiwi-live
    state: present

- name: enable zigzag-live service
  systemd: name=zigzag-live enabled=yes
