---
- name: install translation packages
  command: zigzag-languages -y

- name: install live medium tools
  zypper:
    name:
      - calamares-branding-zigzag
      - zigzag-live-service
      - dracut-kiwi-live
    state: present

- name: enable zigzag-live service
  systemd: name=zigzag-live enabled=yes

# VirtualBox (kernel < 4.13 does not ship with vboxvideo module)
- name: install virtualbox module on leap
  zypper: name=virtualbox-guest-kmp-default state=present
  when: is_leap == true

- name: remove temporary excludedocs zypper option
  lineinfile:
    path: /etc/zypp/zypp.conf
    line: 'rpm.install.excludedocs = yes'
    state: absent
