---
- name: setup fstab for overlayfs
  command: setup-fstab-for-overlayfs

- name: change fstab entry for root to be read-only
  replace:
    path: /etc/fstab
    regexp: '/\s+btrfs\s+'
    replace: '/ btrfs ro,'
