---
- name: set 'solver.onlyRequires = true'
  ini_file:
    path: /etc/zypp/zypp.conf
    create: no
    section: main
    option: solver.onlyRequires
    value: 'true'

- name: set 'solver.cleandepsOnRemove = true'
  ini_file:
    path: /etc/zypp/zypp.conf
    create: no
    section: main
    option: solver.cleandepsOnRemove
    value: 'true'

- import_tasks: repos.yml
