---
- name: install systemd-resolved
  zypper: name=systemd-network state=present

- name: disable netconfig dns resolution
  lineinfile:
    path: /etc/sysconfig/network/config
    regexp: '^NETCONFIG_DNS_POLICY="auto"'
    line: 'NETCONFIG_DNS_POLICY=""'

- name: create resolve directory
  file:
    path: /run/systemd/resolve
    state: directory

- name: populate service facts
  service_facts:

- name: trasition to use stub-resolv.conf
  copy:
    src: /var/run/netconfig/resolv.conf
    dest: /run/systemd/resolve/stub-resolv.conf
  when: ansible_facts.services['systemd-resolved.service'].state == 'inactive'

- name: symlink resolv.conf to resolved stub
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: enable systemd-resolved
  systemd: name=systemd-resolved enabled=yes
