---
- name: setup network
  block:
    - import_tasks: networkmanager.yml
    - import_tasks: dns.yml
  when: role_mode == 'setup'

- import_tasks: dns_symlink.yml
  when: role_mode == 'resolv_symlink'
