---
- name: set 'install_weak_deps=False' dnf option
  ini_file:
    path: /etc/dnf/dnf.conf
    no_extra_spaces: yes
    create: no
    section: main
    option: install_weak_deps
    value: 'False'

# this ensures no cached data is left on the image
- name: make tempfs mount on dnf cache
  mount:
    path: /var/cache/dnf
    src: 'tmpfs'
    fstype: tmpfs
    state: mounted
    fstab: /tmp/tmp.fstab

- name: find all dnf repo files
  find:
    paths: /etc/yum.repos.d/
    patterns: "*.repo"
  register: dnf_repos

- name: ensure no hardcoded repo versions present
  replace:
    path: "{{ item.path }}"
    regexp: "{{ ansible_distribution_version }}"
    replace: '$releasever'
  with_items: "{{ dnf_repos.files }}"

- name: fix broken symlink to gpg key
  file:
    src: /usr/lib/rpm/gnupg/keys/gpg-pubkey-65176565-61a0ee8f.asc
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-openSUSE-Backports
    state: link
