---
- name: install additional cli tools
  zypper:
    name:
      - tree
      - patch
      - colordiff
      - neovim
      - neovim-symlinks
      - bash-completion
      - command-not-found
      - unar
      - 7zip
    state: present
