---
- hosts: all
  vars:
    conf_stage: image_setup
  pre_tasks:
    - import_role: name=kiwi_pre
      when: is_kiwi == true
  post_tasks:
    - import_role: name=kiwi_post
      when: is_kiwi == true
  roles:
    - zypper
    - base
    - sudo
    - apparmor
    - memory
    - network
    - snapper
    - immutable
    - samba
    - desktop
    - polkit
    - fonts
