---
- name: enable time synchronization service
  systemd: name=systemd-timesyncd enabled=yes

- name: enable avahi service
  systemd: name=avahi-daemon enabled=yes

# This file is not provided by aaa_base
# Without it update process won't regenerate grub config
- name: fillup /etc/sysconfig/bootloader
  copy:
    src: sysconfig.bootloader
    dest: /etc/sysconfig/bootloader
    mode: 0644
