---
- import_tasks: packages.yml
- import_tasks: flatpak.yml
- import_tasks: services.yml

# This file is not provided by aaa_base
# Without it update process won't regenerate grub config
- name: fillup /etc/sysconfig/bootloader
  copy:
    src: sysconfig.bootloader
    dest: /etc/sysconfig/bootloader
    mode: 0644
