---
- name: install minimal base
  package:
    name:
      - patterns-base-minimal_base
      - mozilla-nss-certs
      - openSUSE-signkey-cert
    state: present

- name: install kernel and firmware
  package:
    name:
      - kernel-default
      - patterns-zigzag-firmware
    state: present

- name: install bootloader
  package:
    name:
      - grub2-branding-openSUSE
      - grub2-i386-pc
      - grub2-x86_64-efi
      - syslinux
      - shim
    state: present

- name: install utility packages
  package:
    name:
      - sudo
      - rng-tools
      - finger
      - time
      - timezone
      - man
      - psmisc
      - lsof
      - curl
      - less
      - openssh
      - iproute2
      - iputils
      - iw
      - crda
      - audit
      - avahi
      - zigzag-languages
      - bash-completion
      - command-not-found
      - podman
      - toolbox
      - vim
      - rpmconf
      - deltarpm
      - sensors
      - dmidecode
      - hdparm
      - sysfsutils
      - pciutils
      - usbutils
      - fwupd
      - smartmontools
      - cryptsetup
      - iotop
    state: present

- name: install archive utils
  package:
    name:
      - tar
      - unar
      - p7zip
    state: present

- name: install file-system utils
  package:
    name:
      - xfsprogs
      - btrfsprogs
      - btrfsmaintenance
      - e2fsprogs
      - ntfsprogs
      - dosfstools
      - f2fs-tools
    state: present
